### PR TITLE
Move plugin_setting to an on_plugin_import block.

### PR DESCRIPTION
**Pull request by hvoers**
Enable the use of $dsl->schema from other plugins.

### CODE REVIEW

**Comment by hvoers** [comment]
Can you please look at this PR?

**Comment by ironcamel** [comment]
Do the tests pass on this branch?

**Comment by ironcamel** [comment]
Also, why is this approach better? Isn't the current approach simpler?

**Comment by hvoers** [comment]
I am going to download the full dist and run the tests.
So far I only just used the .pm file in a test app.

The rationale for this patch is the following:
I want to use plugins in plugins.
I load Dancer2::Plugin::DBIC in my main app.
In a plugin I can use $dsl->schema('schemaname') but only if it does not call plugin_setting.
Dancer2::Plugin carp's with "DEPRECATED: $plugin calls 'dsl' instead of '\$dsl->dsl'."

**Comment by hvoers** [comment]
Aha, I see.
I did not account for
set plugins => {
    DBIC => {
        foo => {
            schema_class => 'Foo',
            dsn =>  "dbi:SQLite:dbname=$dbfile",
        },
    }
};

I will sleep on it and come back later this week.

**Comment by ironcamel** [comment]
I don't understand what you mean. What exactly did you not account for?

**Comment by hvoers** [comment]
Dynamic config, "set plugins".
I would not do that in a production app
but your use of it in tests must be supported.

It's all about 'how to call plugin_setting'
(which setting from which plugin or which route at what time)

I'm going to test some patches in Dancer2::Plugin;
and come back with an other PR.

**Comment by ironcamel** [comment]
Ah I see. Thanks for looking into this.

**Comment by hvoers** [comment]
Tested a new PR, see that.

**Pull request closed without merging**
